### ISSUE TITLE
Necessary configuration for public URL

### ISSUE THREAD

**Issue by jodesp** [edubadges/edubadges-ui#102]
Hello,

I would like to ask if there is any way to configure specifically the `edubadges-ui` in order to access the application server under a specific domain name/public URL (instead of localhost) for both backend/frontend instances. Currently the UI makes requests towards the localhost backend (at port 8000) and so the public frontend URL isn't able to be functional.

**Comment by oharsta** [comment]
Sorry for the late reply. The https://github.com/edubadges/edubadges-ui/blob/develop/src/util/config.js file contains the configurable URL of the edubadges-server.
